"""Update pws and add M2M table services del cascade

Revision ID: 42d97b263ed1
Revises: d2a802630447
Create Date: 2025-02-09 11:39:34.965517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d97b263ed1'
down_revision: Union[str, None] = 'd2a802630447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_with_services_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_with_service_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_with_service_id'], ['products_with_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_with_services_services_product_with_service_id'), 'products_with_services_services', ['product_with_service_id'], unique=False)
    op.create_index(op.f('ix_products_with_services_services_service_id'), 'products_with_services_services', ['service_id'], unique=False)
    op.add_column('products_with_services', sa.Column('service_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_index('ix_products_with_services_service_id', table_name='products_with_services')
    op.drop_constraint('products_with_services_product_id_fkey', 'products_with_services', type_='foreignkey')
    op.drop_constraint('products_with_services_service_id_fkey', 'products_with_services', type_='foreignkey')
    op.create_foreign_key(None, 'products_with_services', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products_with_services', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_with_services', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products_with_services', type_='foreignkey')
    op.create_foreign_key('products_with_services_service_id_fkey', 'products_with_services', 'services', ['service_id'], ['id'])
    op.create_foreign_key('products_with_services_product_id_fkey', 'products_with_services', 'products', ['product_id'], ['id'])
    op.create_index('ix_products_with_services_service_id', 'products_with_services', ['service_id'], unique=False)
    op.drop_column('products_with_services', 'service_ids')
    op.drop_index(op.f('ix_products_with_services_services_service_id'), table_name='products_with_services_services')
    op.drop_index(op.f('ix_products_with_services_services_product_with_service_id'), table_name='products_with_services_services')
    op.drop_table('products_with_services_services')
    # ### end Alembic commands ###
