"""Add user_id to orders table and create index

Revision ID: 253e8993a03d
Revises: c8b3dedf505d
Create Date: 2025-01-22 20:14:51.890052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253e8993a03d'
down_revision: Union[str, None] = 'c8b3dedf505d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
