"""Update ordersORM

Revision ID: 3e91f319daf6
Revises: 42d97b263ed1
Create Date: 2025-02-10 20:01:19.749741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e91f319daf6'
down_revision: Union[str, None] = '42d97b263ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_with_services_id', sa.Integer(), nullable=False))
    op.drop_index('ix_orders_product_id', table_name='orders')
    op.drop_index('ix_orders_total_price', table_name='orders')
    op.create_index('ix_orders_product_service_id', 'orders', ['product_with_services_id'], unique=False)
    op.create_index(op.f('ix_orders_product_with_services_id'), 'orders', ['product_with_services_id'], unique=False)
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products_with_services', ['product_with_services_id'], ['id'])
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_orders_product_with_services_id'), table_name='orders')
    op.drop_index('ix_orders_product_service_id', table_name='orders')
    op.create_index('ix_orders_total_price', 'orders', ['total_price'], unique=False)
    op.create_index('ix_orders_product_id', 'orders', ['product_id'], unique=False)
    op.drop_column('orders', 'product_with_services_id')
    # ### end Alembic commands ###
