"""Update products model without tsv column russia

Revision ID: d2a802630447
Revises: e608b754b32d
Create Date: 2025-02-02 22:53:12.068293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2a802630447'
down_revision: Union[str, None] = 'e608b754b32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv', table_name='products', postgresql_using='gin')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_tsv', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
