"""Cascade delete m2m tables

Revision ID: f3596e9cc9c2
Revises: 1466bab65729
Create Date: 2025-02-16 10:47:55.069232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3596e9cc9c2"
down_revision: Union[str, None] = "1466bab65729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "order_products_order_id_fkey", "order_products", type_="foreignkey"
    )
    op.drop_constraint(
        "order_products_product_id_fkey", "order_products", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "order_products", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "order_products", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "order_services_service_id_fkey", "order_services", type_="foreignkey"
    )
    op.drop_constraint(
        "order_services_order_id_fkey", "order_services", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "order_services", "services", ["service_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "order_services", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("orders", "total_price", existing_type=sa.NUMERIC(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "total_price", existing_type=sa.NUMERIC(), nullable=False)
    op.drop_constraint(None, "order_services", type_="foreignkey")
    op.drop_constraint(None, "order_services", type_="foreignkey")
    op.create_foreign_key(
        "order_services_order_id_fkey", "order_services", "orders", ["order_id"], ["id"]
    )
    op.create_foreign_key(
        "order_services_service_id_fkey",
        "order_services",
        "services",
        ["service_id"],
        ["id"],
    )
    op.drop_constraint(None, "order_products", type_="foreignkey")
    op.drop_constraint(None, "order_products", type_="foreignkey")
    op.create_foreign_key(
        "order_products_product_id_fkey",
        "order_products",
        "products",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "order_products_order_id_fkey", "order_products", "orders", ["order_id"], ["id"]
    )
    # ### end Alembic commands ###
